//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KeyboardEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyboardEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminal.Properties.KeyboardEnglish", typeof(KeyboardEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,3,4,5,6,7,8,9,0.
        /// </summary>
        public static string Row1Lower {
            get {
                return ResourceManager.GetString("Row1Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,3,4,5,6,7,8,9,0.
        /// </summary>
        public static string Row1Upper {
            get {
                return ResourceManager.GetString("Row1Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q,w,e,r,t,y,u,i,o,p.
        /// </summary>
        public static string Row2Lower {
            get {
                return ResourceManager.GetString("Row2Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q,W,E,R,T,Y,U,I,O,P.
        /// </summary>
        public static string Row2Upper {
            get {
                return ResourceManager.GetString("Row2Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,s,d,f,g,h,j,k,l.
        /// </summary>
        public static string Row3Lower {
            get {
                return ResourceManager.GetString("Row3Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,S,D,F,G,H,J,J,K,L.
        /// </summary>
        public static string Row3Upper {
            get {
                return ResourceManager.GetString("Row3Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z,x,c,v,b,n,m.
        /// </summary>
        public static string Row4Lower {
            get {
                return ResourceManager.GetString("Row4Lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z,X,C,V,B,N,M.
        /// </summary>
        public static string Row4Upper {
            get {
                return ResourceManager.GetString("Row4Upper", resourceCulture);
            }
        }
    }
}
