//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1!k699(ywTk!le8jdh7673gh{)y3Hyfhf67!!")]
        public string BillValidatorSecureKey {
            get {
                return ((string)(this["BillValidatorSecureKey"]));
            }
            set {
                this["BillValidatorSecureKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://192.168.10.162:55555/socket/out")]
        public string BillValidatorServerSocket {
            get {
                return ((string)(this["BillValidatorServerSocket"]));
            }
            set {
                this["BillValidatorServerSocket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.10.162:55555")]
        public string BillValidatorServerIpAndPort {
            get {
                return ((string)(this["BillValidatorServerIpAndPort"]));
            }
            set {
                this["BillValidatorServerIpAndPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("am,en,ru")]
        public string KeyboardLanguages {
            get {
                return ((string)(this["KeyboardLanguages"]));
            }
            set {
                this["KeyboardLanguages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("etytwh5624gadf%^gh786745JHHJjkjhdgb9834rhjb3rthreh9gh9834buibgyub8g7ergh956yjh76j" +
            "-3f29879")]
        public string TerminalKey {
            get {
                return ((string)(this["TerminalKey"]));
            }
            set {
                this["TerminalKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://payway.am")]
        public string BackServerURL {
            get {
                return ((string)(this["BackServerURL"]));
            }
            set {
                this["BackServerURL"] = value;
            }
        }
    }
}
